### ISSUE TITLE
question

### ISSUE THREAD

**Issue by shikulja** [unknownbrackets/maxcso#40] opened 2020-08-06 06:28 UTC
as I understand it, does not know how to compress CD images of ps2 games
of these I found
Harry Potter and the Chamber of Secrets
Gradius V
World Destruction League - Thunder Tanks
A-Train 6
i.e. quite a lot of ps2 games use CD, will the ability to compress them be added to cso?

**Comment by unknownbrackets** [comment] 2020-08-06 07:15
It does support CDs, assuming they are mode 1 discs.  See #13.

I don't think he PS2 actually supported reading sub data.  But I think World Destruction League - Thunder Tanks is actually a PS1 game?  If so, it likely does use sub data and is indeed not supported.  Again, see #13.

Even if maxcso supported such discs, I'm aware of exactly zero emulators or other tools that would be able to read the produced CSO files.  For example, Play! and pcsx2 also do not support mode 2 CSO files.

Closing as a duplicate of #13.

-[Unknown]

**Closed by unknownbrackets** 2020-08-06 07:15 UTC
